name: Build and Push Docker Image

on:
  push:
    paths:
      - "version.txt"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Generate Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Read Version
        id: version
        run: |
          VERSION=$(cat version.txt | tr -d '[:space:]')
          echo "ðŸ“¦ Version: $VERSION"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: openclaw:latest
          outputs: type=docker,dest=openclaw.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Export Docker Image
        uses: actions/upload-artifact@v6
        with:
          name: openclaw-docker-image
          path: openclaw.tar
          retention-days: 1

  deploy:
    name: Deploy Docker Image to Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Import Docker Image
        uses: actions/download-artifact@v7
        with:
          name: openclaw-docker-image
          path: images

      - name: Upload Docker Image
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: images/*
          target: ${{ secrets.IMAGE_DIR_PATH }}
          strip_components: 1

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.IMAGE_DIR_PATH }}

            docker compose down gateway
            docker load -i openclaw.tar
            docker compose up -d gateway
            docker image prune -f
